# Horse Combat Revamped Plugin Configuration (Minimal)

# Lance settings
lance:
  displayName: "§5Lance of Momentum"
  lore:
    - "§7Use this lance to knock players off their horses!"
    - "§7Build momentum for increased damage!"
  customModelData: 12345

  # Fancy lance settings
  fancyDisplayName: "§d§lEnchanted Lance of Momentum"
  fancyLore:
    - "§5A mystical lance infused with purple energy"
    - "§7Use this lance to knock players off their horses!"
    - "§7Deals more damage than a regular lance."
  fancyCustomModelData: 12346

# Combat settings
combat:
  maxDamage: 10.0
  footDamage: 0.5
  footDamageMobs: 1.0
  mobDamageMultiplier: 1.5
  fancyLanceMultiplier: 1.3     # Damage multiplier for fancy lance
  fancyLanceFootMultiplier: 1.2 # Damage multiplier for fancy lance on foot
  knockoffThreshold: 50
  slownessDuration: 100
  slownessLevel: 1
  momentumReduction: 30         # How much momentum is reduced after an attack

# Towny integration
towny:
  enabled: true
  # Respect Towny PvP settings
  respectTownPvP: true
  # Allow lance combat in wilderness only
  wildernessOnly: false
  # Whether mobs in towns should be protected
  protectMobs: true

# WorldGuard integration
worldguard:
  enabled: true
  # Whether to respect WorldGuard region flags
  respectRegionFlags: true
  # Register custom flags on startup
  registerCustomFlags: true

# Momentum settings
momentum:
  movementThreshold: 0.05   # Minimum distance to consider horse moving
  stallTimeMs: 500          # Time in milliseconds before momentum starts decaying when stopped
  turnThreshold: 30.0       # Angle change threshold for detecting sharp turns
  turnLoss: 10              # Momentum loss when making sharp turns
  straightGain: 1           # Momentum gain per tick when moving straight
  initialDecayRate: 5       # Initial decay rate when stopping
  maxDecayRate: 20          # Maximum decay rate per tick when standing still
  boostDecayRate: 3         # How much decay rate increases each tick when stopped

  # NEW: Emergency brake settings
  emergencyBrakeLoss: 60    # Instant momentum loss when emergency braking
  emergencyDecayRate: 15    # Rapid decay rate after emergency brake

# Display settings
display:
  # ONLY ACTION BAR - XP bar disabled completely
  useActionBar: true        # Show momentum on the action bar
  # Gradient block bar format: Momentum: ████████████████████ (87)
  gradientBlocks: true      # Use colorful block bar instead of text

# Visual effects settings
effects:
  showTurnEffects: true     # Show particles and play sounds on turns
  showStopEffects: true     # Show particles and play sounds when stopping
  showSlowdownEffects: true # Show particles and play sounds when slowing down
  playMountEffect: true     # Play effect when mounting a horse

  # Particle effect definitions
  particleEffects:
    # Impact effects
    lowImpact:
      particle: "CRIT"
      count: 5
      offsetX: 0.3
      offsetY: 0.3
      offsetZ: 0.3
      speed: 0.1
      sound: "ENTITY_SLIME_SQUISH"
      volume: 0.4
      pitch: 1.1

    mediumImpact:
      particle: "CRIT_MAGIC"
      count: 10
      offsetX: 0.4
      offsetY: 0.4
      offsetZ: 0.4
      speed: 0.2
      sound: "ENTITY_SLIME_SQUISH"
      volume: 0.8
      pitch: 0.7

    highImpact:
      particle: "EXPLOSION_NORMAL"
      count: 5
      offsetX: 0.5
      offsetY: 0.5
      offsetZ: 0.5
      speed: 0.2
      sound: "ENTITY_SLIME_JUMP"
      volume: 1.0
      pitch: 0.5

    # Momentum effects
    lowMomentum:
      particle: "CLOUD"
      count: 1
      offsetX: 0.1
      offsetY: 0.0
      offsetZ: 0.1
      speed: 0.0

    mediumMomentum:
      particle: "CLOUD"
      count: 2
      offsetX: 0.1
      offsetY: 0.0
      offsetZ: 0.1
      speed: 0.01

    highMomentum:
      particle: "FLAME"
      count: 2
      offsetX: 0.1
      offsetY: 0.0
      offsetZ: 0.1
      speed: 0.02

    # Other effects
    mount:
      particle: "CLOUD"
      count: 15
      offsetX: 0.3
      offsetY: 0.2
      offsetZ: 0.3
      speed: 0.05
      sound: "ENTITY_HORSE_SADDLE"
      volume: 0.8
      pitch: 1.0

    knockoff:
      particle: "EXPLOSION_NORMAL"
      count: 3
      offsetX: 0.2
      offsetY: 0.2
      offsetZ: 0.2
      speed: 0.1
      sound: "ENTITY_PLAYER_ATTACK_KNOCKBACK"
      volume: 0.7
      pitch: 1.2

    footCombat:
      particle: "SWEEP_ATTACK"
      count: 1
      offsetX: 0.2
      offsetY: 0.0
      offsetZ: 0.2
      speed: 0.0
      sound: "ENTITY_PLAYER_ATTACK_SWEEP"
      volume: 0.5
      pitch: 1.0

# Message settings
messages:
  lanceReceived: "§dYou have received a Lance of Momentum!"
  fancyLanceReceived: "§5You have received an Enchanted Lance of Momentum!"
  noPermission: "§cYou don't have permission to use this command."

# Sound settings
sounds:
  hit: "ENTITY_SLIME_ATTACK"
  critical: "ENTITY_PLAYER_ATTACK_CRIT"
  knockoff: "ENTITY_PLAYER_ATTACK_KNOCKBACK"

# Debug mode - ENABLE THIS to see what's happening with momentum
debug: true