name: HorseCombatRevampedAgain
version: '2.0'
main: org.SakyQ.horsecombatRevampedAgain.HorsecombatRevampedAgain
api-version: '1.20.1'
authors: [SakyQ]
description: Overhaul of the horse combat system
softdepend: [Towny, PlaceholderAPI]

commands:
  horsecombat:
    description: Main command for HorseCombat
    usage: /<command> [help|reload|debug|checkregion|listregs]
    aliases: [hc]

  givelance:
    description: Give a lance to yourself or another player
    usage: /<command> [player]
    aliases: [lance]

  hcbypass:
    description: Toggle Towny protection bypass for admins
    usage: /<command> [toggle|on|off|status]
    aliases: [hctb]

  hcadmin:
    description: Open the HorseCombat admin GUI
    usage: /<command>
    aliases: [hca]

  horseegg:
    description: Get a custom horse spawn egg
    usage: /<command> <type>
    aliases: [hegg]

permissions:
  horsecombat.admin:
    description: Allows access to all HorseCombat admin commands
    default: op
    children:
      horsecombat.admin.reload: true
      horsecombat.admin.gui: true
      horsecombat.admin.townybypass: true
      horsecombat.debug: true
      horsecombat.givelance: true
      horsecombat.horseegg: true

  horsecombat.admin.reload:
    description: Allows reloading the HorseCombat configuration
    default: op

  horsecombat.admin.gui:
    description: Allows access to the HorseCombat admin GUI
    default: op

  horsecombat.admin.townybypass:
    description: Allows bypassing Towny protection
    default: op

  horsecombat.debug:
    description: Allows toggling debug mode
    default: op

  horsecombat.givelance:
    description: Allows giving a lance to players
    default: op

  horsecombat.horseegg:
    description: Allows spawning custom horse eggs
    default: op